# Generated by Django 5.1.6 on 2025-02-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_location', models.CharField(blank=True, max_length=255, null=True)),
                ('in_cooperation_with', models.TextField(blank=True, null=True)),
                ('teaching_language', models.CharField(blank=True, max_length=100, null=True)),
                ('language_level_of_course', models.TextField(blank=True, null=True)),
                ('date_info', models.TextField(blank=True, null=True)),
                ('target_group', models.TextField(blank=True, null=True)),
                ('description_content', models.TextField(blank=True, null=True)),
                ('recognised_language_exams', models.CharField(blank=True, max_length=255, null=True)),
                ('other_degrees_awarded', models.CharField(blank=True, max_length=255, null=True)),
                ('ects_points', models.IntegerField(blank=True, null=True)),
                ('avg_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('avg_participants_per_group', models.IntegerField(blank=True, null=True)),
                ('dates_and_costs', models.TextField(blank=True, null=True)),
                ('price_includes', models.TextField(blank=True, null=True)),
                ('funding_info', models.TextField(blank=True, null=True)),
                ('language_requirements', models.TextField(blank=True, null=True)),
                ('submit_application_to', models.TextField(blank=True, null=True)),
                ('accommodation_organised', models.BooleanField(default=False)),
                ('type_of_accommodation', models.TextField(blank=True, null=True)),
                ('meals', models.TextField(blank=True, null=True)),
                ('social_and_leisure_programme_offered', models.BooleanField(default=False)),
                ('social_and_leisure_programme_description', models.TextField(blank=True, null=True)),
                ('free_internet_access', models.BooleanField(default=False)),
                ('support_in_visa_matters', models.BooleanField(default=False)),
                ('pick_up_service', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('university_description', models.TextField(blank=True, null=True)),
                ('university_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
