# Generated by Django 5.1.6 on 2025-02-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='accommodation_organised',
            new_name='has_grade_requirement',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='free_internet_access',
            new_name='is_combined_degree',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='pick_up_service',
            new_name='is_gre_optional',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='social_and_leisure_programme_offered',
            new_name='is_gre_required',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='support_in_visa_matters',
            new_name='is_joint_degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='avg_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='avg_participants_per_group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='dates_and_costs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ects_points',
        ),
        migrations.RemoveField(
            model_name='course',
            name='email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='funding_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='in_cooperation_with',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language_level_of_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language_requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='course',
            name='other_degrees_awarded',
        ),
        migrations.RemoveField(
            model_name='course',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_includes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='recognised_language_exams',
        ),
        migrations.RemoveField(
            model_name='course',
            name='social_and_leisure_programme_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='submit_application_to',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teaching_language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type_of_accommodation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='website',
        ),
        migrations.AddField(
            model_name='course',
            name='cerf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='grade_system',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='gre_score_required',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ielts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='qualitative_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='summer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='toefl_ibt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='toefl_pbt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='winter_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
