# Generated by Django 5.1.6 on 2025-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_grade_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uni_assist',
            field=models.BooleanField(default=False),
        ),
    ]
